import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const studioPage = readFileSync("app/app/page.tsx", "utf8");
const settingsPage = readFileSync("app/settings/page.tsx", "utf8");
const rootLayout = readFileSync("app/layout.tsx", "utf8");
const accountMenuBehavior = readFileSync("app/components/AccountMenuBehavior.tsx", "utf8");
const globalsCss = readFileSync("app/globals.css", "utf8");

test("studio account menu acts as a workspace command center", () => {
  assert.match(studioPage, /AccountAvatar/);
  assert.match(studioPage, /imageUrl\?: string/);
  assert.match(studioPage, /reference\?: string/);
  assert.match(studioPage, /studio-account-identity/);
  assert.match(studioPage, /accountReferenceLabel/);
  assert.match(studioPage, /Account ref \{accountReferenceLabel\}/);
  assert.match(studioPage, /className="studio-account-reference"/);
  assert.match(studioPage, /className="studio-account-reference-copy"/);
  assert.match(studioPage, /studio-account-insights/);
  assert.match(studioPage, /Account status summary/);
  assert.match(studioPage, /accountMenuNextStep/);
  assert.match(studioPage, /studio-account-next-step/);
  assert.match(studioPage, /Recommended workspace action/);
  assert.match(studioPage, /Start with a resume/);
  assert.match(studioPage, /Add the job target/);
  assert.match(studioPage, /Ready to tailor/);
  assert.match(studioPage, /Create the next export/);
  assert.match(studioPage, /Premium export locked/);
  assert.match(studioPage, /onAccountMenuNextStep/);
  assert.match(studioPage, /document\.getElementById\("input"\)\?\.scrollIntoView/);
  assert.match(studioPage, /document\.getElementById\("target"\)\?\.scrollIntoView/);
  assert.match(studioPage, /void onRun\(\)/);
  assert.match(studioPage, /void onExportSelectedFormat\(\)/);
  assert.match(studioPage, /void syncLocalHistoryToAccount\(\)/);
  assert.match(studioPage, /openHistoryPanel\(\)/);
  assert.match(studioPage, /href="\/templates"/);
  assert.match(studioPage, /href="\/settings#billing"/);
  assert.match(studioPage, /href="\/help"/);
  assert.match(studioPage, /href="\/status"/);
  assert.match(studioPage, /href="\/updates"/);
  assert.match(studioPage, /href="\/support"/);
  assert.match(studioPage, /accountBillingSupportHref/);
  assert.match(studioPage, /category:\s*"billing"/);
  assert.match(studioPage, /subject:\s*"Billing or Premium access"/);
  assert.match(studioPage, /href=\{accountBillingSupportHref\}/);
  assert.match(studioPage, /Help center/);
  assert.match(studioPage, /System status/);
  assert.match(studioPage, /Product updates/);
  assert.match(studioPage, /Billing support/);
  assert.match(studioPage, /Saved projects/);
  assert.match(studioPage, /DOCX and TXT/);
  assert.match(studioPage, /recentAccountProjects/);
  assert.match(studioPage, /studio-account-recent/);
  assert.match(studioPage, /Recent projects/);
  assert.match(studioPage, /savedRunHistoryHref/);
  assert.match(studioPage, /studio-account-sync-actions/);
  assert.match(studioPage, /syncableLocalHistoryCount\s*\?/);
  assert.match(studioPage, /void syncLocalHistoryToAccount\(\)/);
  assert.match(studioPage, /Save browser/);
  assert.match(studioPage, /studio-account-utilities/);
  assert.match(studioPage, /href="\/api\/account\/export"/);
  assert.match(studioPage, /Export account record/);
  assert.match(studioPage, /accountSummary/);
  assert.match(studioPage, /accountSavedProjectCount/);
  assert.match(studioPage, /accountSupportRequestCount/);
  assert.match(studioPage, /Support history/);
  assert.match(studioPage, /href="\/settings#support"/);
});

test("account menu layout has responsive status cards", () => {
  assert.match(globalsCss, /\.account-avatar-photo\s*\{/);
  assert.match(globalsCss, /\.account-avatar-initials\s*\{/);
  assert.match(globalsCss, /\.public-account-reference,\s*\.studio-account-reference\s*\{(?=[^}]*display:\s*flex)(?=[^}]*flex-wrap:\s*wrap)(?=[^}]*max-width:\s*100%)[^}]*\}/s);
  assert.match(globalsCss, /\.public-account-reference-copy,\s*\.studio-account-reference-copy\s*\{(?=[^}]*display:\s*inline-flex)(?=[^}]*min-height:\s*26px)(?=[^}]*overflow-wrap:\s*anywhere)[^}]*\}/s);
  assert.match(globalsCss, /\.studio-account-insights\s*\{/);
  assert.match(globalsCss, /\.studio-account-insights strong,\s*\.studio-account-insights span\s*\{(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*text-wrap:\s*balance)[^}]*\}/s);
  assert.doesNotMatch(globalsCss, /\.studio-account-insights strong,\s*\.studio-account-insights span\s*\{[^}]*text-overflow:\s*ellipsis/s);
  assert.match(globalsCss, /@container studio-account-popover \(max-width: 360px\)/);
  assert.match(globalsCss, /html\[data-theme="dark"\] \.studio-account-insights a/);
  assert.match(globalsCss, /\.studio-account-recent\s*\{(?=[^}]*display:\s*grid)(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(globalsCss, /\.studio-account-recent-link\s*\{(?=[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto)(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(globalsCss, /\.studio-account-recent-link\s+strong\s*\{(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*text-wrap:\s*balance)[^}]*\}/s);
  assert.match(globalsCss, /\.studio-account-sync-actions\s*\{(?=[^}]*display:\s*grid)(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(globalsCss, /\.studio-account-sync-actions\s+button\s*\{(?=[^}]*width:\s*100%)(?=[^}]*min-width:\s*0)(?=[^}]*text-wrap:\s*balance)[^}]*\}/s);
  assert.match(globalsCss, /\.studio-account-next-step\s*\{(?=[^}]*display:\s*grid)(?=[^}]*grid-template-columns:\s*34px\s+minmax\(0,\s*1fr\))(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(globalsCss, /\.studio-account-next-step-copy\s+span,\s*\.studio-account-next-step-copy\s+strong,\s*\.studio-account-next-step-copy\s+small\s*\{(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*text-wrap:\s*balance)[^}]*\}/s);
  assert.match(globalsCss, /\.studio-account-next-step-action\s*\{(?=[^}]*grid-column:\s*1\s*\/\s*-1)(?=[^}]*min-width:\s*0)(?=[^}]*text-wrap:\s*balance)(?=[^}]*white-space:\s*normal)[^}]*\}/s);
  assert.match(globalsCss, /html\[data-theme="dark"\]\s+\.studio-account-next-step/);
  assert.match(globalsCss, /html\[data-theme="dark"\]\s+\.studio-account-next-step-action/);
  assert.match(globalsCss, /\.studio-account-utilities\s*\{(?=[^}]*display:\s*grid)(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(globalsCss, /\.studio-account-utilities\s+a\s*\{(?=[^}]*min-width:\s*0)(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*text-wrap:\s*balance)[^}]*\}/s);
  assert.match(globalsCss, /html\[data-theme="dark"\] \.studio-account-utilities a/);
});

test("settings topbar exposes account, project, usage, and billing controls", () => {
  assert.match(settingsPage, /AccountAvatar/);
  assert.match(settingsPage, /accountAvatarUrl\(user\)/);
  assert.match(settingsPage, /settings-account-menu/);
  assert.match(settingsPage, /data-account-menu="true"/);
  assert.match(settingsPage, /aria-label="Open account menu"/);
  assert.match(settingsPage, /aria-haspopup="menu"/);
  assert.match(settingsPage, /aria-expanded="false"/);
  assert.match(settingsPage, /title=\{displayName \|\| user\.email \|\| "RoleForge account"\}/);
  assert.match(settingsPage, /\{displayName \|\| "RoleForge account"\}/);
  assert.match(settingsPage, /\$\{user\.email\} · \$\{displayPlanLabel\}/);
  assert.match(settingsPage, /accountReference\(user\.id\)/);
  assert.match(settingsPage, /Account ref \{accountReferenceLabel\}/);
  assert.match(settingsPage, /className="studio-account-reference"/);
  assert.match(settingsPage, /className="studio-account-reference-copy"/);
  assert.match(settingsPage, /recentProjectSummaries/);
  assert.match(settingsPage, /settings-account-recent/);
  assert.match(settingsPage, /Recent projects/);
  assert.match(settingsPage, /recentProjectSummaries\.map/);
  assert.match(settingsPage, /href=\{project\.href\}/);
  assert.match(settingsPage, /settings-account-utilities/);
  assert.match(settingsPage, /settingsAccountNextActions/);
  assert.match(settingsPage, /settings-account-next-actions/);
  assert.match(settingsPage, /Recommended account actions/);
  assert.match(settingsPage, /settingsAccountBillingActionLabel/);
  assert.match(settingsPage, /Manage billing/);
  assert.match(settingsPage, /View Premium/);
  assert.match(settingsPage, /Billing status/);
  assert.match(settingsPage, /settingsAccountProjectActionLabel/);
  assert.match(settingsPage, /Restore project/);
  assert.match(settingsPage, /Start project/);
  assert.match(settingsPage, /settingsAccountSupportActionLabel/);
  assert.match(settingsPage, /Support history/);
  assert.match(settingsPage, /Contact support/);
  assert.match(settingsPage, /settingsAccountNextActions\.map/);
  assert.match(settingsPage, /href="\/api\/account\/export"/);
  assert.match(settingsPage, /Export account record/);
  assert.match(settingsPage, /href="#security"/);
  assert.match(settingsPage, /href="#preferences"/);
  assert.match(settingsPage, /href="#projects"/);
  assert.match(settingsPage, /href="#usage"/);
  assert.match(settingsPage, /href="#billing"/);
  assert.match(settingsPage, /href="\/help"/);
  assert.match(settingsPage, /href="\/status"/);
  assert.match(settingsPage, /href="\/updates"/);
  assert.match(settingsPage, /href="\/support"/);
  assert.match(settingsPage, /Help center/);
  assert.match(settingsPage, /System status/);
  assert.match(settingsPage, /Product updates/);
  assert.match(settingsPage, /Contact support/);
  assert.match(settingsPage, /Recent support/);
  assert.match(settingsPage, /settings-account-support-recent/);
  assert.match(settingsPage, /supportRequestCount/);
  assert.match(settingsPage, /supportOverviewValue/);
  assert.match(settingsPage, /projectCount \? `\$\{projectCountLabel\} saved` : "Start first project"/);
  assert.match(settingsPage, /<strong>\{supportOverviewValue\}<\/strong>/);
  assert.match(settingsPage, /href="\/app#history"/);
  assert.match(settingsPage, /action="\/auth\/signout"/);
});

test("global account details menus close on outside click escape and navigation actions", () => {
  assert.match(rootLayout, /import \{ AccountMenuBehavior \}/);
  assert.match(rootLayout, /<AccountMenuBehavior \/>/);
  assert.match(accountMenuBehavior, /"use client"/);
  assert.match(accountMenuBehavior, /details\[data-account-menu\]\[open\]/);
  assert.match(accountMenuBehavior, /accountMenuSummary/);
  assert.match(accountMenuBehavior, /syncMenuState/);
  assert.match(accountMenuBehavior, /setAttribute\("aria-expanded",\s*menu\.open \? "true" : "false"\)/);
  assert.match(accountMenuBehavior, /closeOtherMenus/);
  assert.match(accountMenuBehavior, /currentFocusedMenu/);
  assert.match(accountMenuBehavior, /document\.addEventListener\("pointerdown",\s*handlePointerDown\)/);
  assert.match(accountMenuBehavior, /target\.closest(?:<HTMLDetailsElement>)?\("details\[data-account-menu\]"\)/);
  assert.match(accountMenuBehavior, /target\.closest\("summary"\)/);
  assert.match(accountMenuBehavior, /target\.closest\("a, button\[type='submit'\]"\)/);
  assert.match(accountMenuBehavior, /event\.key !== "Escape"/);
  assert.match(accountMenuBehavior, /event\.preventDefault\(\)/);
  assert.match(accountMenuBehavior, /restoreFocus/);
  assert.match(accountMenuBehavior, /\.focus\(\)/);
  assert.match(accountMenuBehavior, /document\.addEventListener\("toggle",\s*handleToggle,\s*true\)/);
  assert.match(accountMenuBehavior, /document\.addEventListener\("focusin",\s*handleFocusIn\)/);
  assert.match(accountMenuBehavior, /if \(menu\.open\) closeOtherMenus\(menu\)/);
  assert.match(accountMenuBehavior, /removeAttribute\("open"\)/);
});

test("settings account recent projects inherit overflow-safe menu layout", () => {
  assert.match(globalsCss, /\.settings-account-recent\s*\{(?=[^}]*display:\s*grid)(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-account-recent-link\s*\{(?=[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto)(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-account-recent-link\s+strong\s*\{(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*text-wrap:\s*balance)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-account-next-actions\s*\{(?=[^}]*margin-bottom:\s*12px)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-account-next-actions\s+a\s*\{(?=[^}]*min-height:\s*40px)[^}]*\}/s);
  assert.match(globalsCss, /html\[data-theme="dark"\]\s+\.studio-account-next-actions\s+a/);
});

test("settings saved project management rows avoid squeezed action columns", () => {
  assert.match(globalsCss, /#projects\.settings-section\s*\{(?=[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\))[^}]*\}/s);
  assert.match(globalsCss, /#projects\s+\.settings-section-panel\s*\{(?=[^}]*inline-size:\s*100%)(?=[^}]*max-inline-size:\s*100%)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-project-item\s*\{(?=[^}]*display:\s*grid)(?=[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\))(?=[^}]*container:\s*settings-project-card\s*\/\s*inline-size)(?=[^}]*overflow:\s*hidden)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-project-summary,\s*\.settings-project-controls\s*\{(?=[^}]*display:\s*grid)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-project-summary\s*\{(?=[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto)(?=[^}]*align-items:\s*start)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-project-controls\s*\{(?=[^}]*inline-size:\s*100%)(?=[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\))(?=[^}]*overflow:\s*hidden)(?=[^}]*border-top:\s*1px\s+solid)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-project-controls\s*>\s*\*\s*\{(?=[^}]*min-inline-size:\s*0)(?=[^}]*max-inline-size:\s*100%)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-project-stage-form,\s*\.settings-project-kit,\s*\.settings-project-delete\s*\{(?=[^}]*grid-column:\s*1\s*\/\s*-1)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-project-item\s+small\s*\{(?=[^}]*justify-self:\s*start)(?=[^}]*max-width:\s*100%)[^}]*\}/s);
  assert.match(globalsCss, /\.settings-project-stage-controls\s*\{(?=[^}]*grid-template-columns:\s*repeat\(auto-fit,\s*minmax\(min\(100%,\s*132px\),\s*1fr\)\))[^}]*\}/s);
  assert.match(globalsCss, /\.settings-project-kit-grid\s*\{(?=[^}]*grid-template-columns:\s*repeat\(auto-fit,\s*minmax\(min\(100%,\s*148px\),\s*1fr\)\))[^}]*\}/s);
  assert.match(globalsCss, /@container\s+settings-project-card\s+\(max-width:\s*680px\)\s*\{[\s\S]*?\.settings-project-stage-controls,\s*\.settings-project-kit-grid\s*\{[^}]*grid-template-columns:\s*repeat\(auto-fit,\s*minmax\(min\(100%,\s*128px\),\s*1fr\)\)/s);
  assert.match(globalsCss, /@container\s+settings-project-card\s+\(max-width:\s*560px\)\s*\{[\s\S]*?\.settings-project-summary,\s*\.settings-project-controls,\s*\.settings-project-rename-row,\s*\.settings-project-delete-row\s*\{[^}]*grid-template-columns:\s*1fr/s);
});
