import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const publicAccountMenu = readFileSync("app/components/PublicAccountMenu.tsx", "utf8");
const accountReferenceCopyButton = readFileSync("app/components/AccountReferenceCopyButton.tsx", "utf8");
const authStatusRoute = readFileSync("app/api/auth/status/route.ts", "utf8");
const helpPage = readFileSync("app/help/page.tsx", "utf8");
const statusPage = readFileSync("app/status/page.tsx", "utf8");
const supportPage = readFileSync("app/support/page.tsx", "utf8");
const updatesPage = readFileSync("app/updates/page.tsx", "utf8");
const stylesheet = readFileSync("app/globals.css", "utf8");

test("public account menu turns static topbars into signed-in command centers", () => {
  assert.match(publicAccountMenu, /"use client"/);
  assert.match(publicAccountMenu, /fetch\("\/api\/auth\/status"/);
  assert.match(publicAccountMenu, /credentials:\s*"same-origin"/);
  assert.match(publicAccountMenu, /AccountReferenceCopyButton/);
  assert.match(accountReferenceCopyButton, /writeClipboardText\(referenceLabel\)/);
  assert.match(publicAccountMenu, /useState<PublicAccountStatus \| null \| undefined>\(undefined\)/);
  assert.match(publicAccountMenu, /const loading = status === undefined/);
  assert.match(publicAccountMenu, /if \(loading\)/);
  assert.match(publicAccountMenu, /public-account-loading/);
  assert.match(publicAccountMenu, /aria-busy="true"/);
  assert.match(publicAccountMenu, /aria-label="Loading account menu"/);
  assert.match(publicAccountMenu, /Loading account menu/);
  assert.match(publicAccountMenu, /currentPagePath/);
  assert.match(publicAccountMenu, /window\.location\.pathname/);
  assert.match(publicAccountMenu, /window\.location\.search/);
  assert.match(publicAccountMenu, /window\.location\.hash/);
  assert.match(publicAccountMenu, /encodeURIComponent\(currentPagePath\(\)\)/);
  assert.match(publicAccountMenu, /window\.location\.assign/);
  assert.match(publicAccountMenu, /AccountAvatar/);
  assert.match(publicAccountMenu, /data-account-menu="true"/);
  assert.match(publicAccountMenu, /aria-label="Open account menu"/);
  assert.match(publicAccountMenu, /aria-haspopup="menu"/);
  assert.match(publicAccountMenu, /aria-expanded="false"/);
  assert.match(publicAccountMenu, /reference\?: string/);
  assert.match(publicAccountMenu, /accountReferenceLabel/);
  assert.match(publicAccountMenu, /Account ref \{accountReferenceLabel\}/);
  assert.match(publicAccountMenu, /referenceLabel=\{accountReferenceLabel\}/);
  assert.match(publicAccountMenu, /public-account-reference-copy/);
  assert.match(publicAccountMenu, /Public page account summary/);
  assert.match(publicAccountMenu, /href="\/settings#billing"/);
  assert.match(publicAccountMenu, /href="\/settings#exports"/);
  assert.match(publicAccountMenu, /href="\/settings#usage"/);
  assert.match(publicAccountMenu, /href="\/settings#support"/);
  assert.match(publicAccountMenu, /href="\/settings#projects"/);
  assert.match(publicAccountMenu, /href="\/templates"/);
  assert.match(publicAccountMenu, /href="\/status"/);
  assert.match(publicAccountMenu, /href="\/updates"/);
  assert.match(publicAccountMenu, /Recommended account actions/);
  assert.match(publicAccountMenu, /billingActionLabel/);
  assert.match(publicAccountMenu, /projectActionLabel/);
  assert.match(publicAccountMenu, /supportActionLabel/);
  assert.match(publicAccountMenu, /Resume work/);
  assert.match(publicAccountMenu, /Manage billing/);
  assert.match(publicAccountMenu, /View Premium/);
  assert.match(publicAccountMenu, /Billing status/);
  assert.match(publicAccountMenu, /Restore project/);
  assert.match(publicAccountMenu, /Start project/);
  assert.match(publicAccountMenu, /Contact support/);
  assert.match(publicAccountMenu, /href=\{supportHref\}/);
  assert.match(publicAccountMenu, /href="\/api\/account\/export"/);
  assert.match(publicAccountMenu, /Export account record/);
  assert.match(publicAccountMenu, /Support history/);
  assert.match(publicAccountMenu, /savedProjectCount/);
  assert.match(publicAccountMenu, /supportRequestCount/);
  assert.match(publicAccountMenu, /operations\?:/);
  assert.match(publicAccountMenu, /supportAdmin\?: boolean/);
  assert.match(publicAccountMenu, /const supportAdmin = Boolean\(status\?\.operations\?\.supportAdmin\)/);
  assert.match(publicAccountMenu, /supportAdmin \? <Link href="\/admin\/support">/);
  assert.match(publicAccountMenu, /Support inbox/);
  assert.match(publicAccountMenu, /countLabel/);
  assert.match(publicAccountMenu, /action="\/auth\/signout"/);
  assert.match(publicAccountMenu, /href="\/login\?next=\/app&account=signin-required"/);
  assert.match(publicAccountMenu, /Sign in/);
});

test("auth status exposes safe account counts for public menus", () => {
  assert.match(authStatusRoute, /accountReference/);
  assert.match(authStatusRoute, /const userId = !error && data\.user \? data\.user\.id : ""/);
  assert.match(authStatusRoute, /reference:\s*accountReference\(userId\)/);
  assert.doesNotMatch(authStatusRoute, /\n\s*id:\s*data\.user\.id/);
  assert.match(authStatusRoute, /countAccountRows/);
  assert.match(authStatusRoute, /table:\s*"resume_projects"\s*\|\s*"support_requests"/);
  assert.match(authStatusRoute, /\.select\("id",\s*\{\s*count:\s*"exact",\s*head:\s*true\s*\}\)/);
  assert.match(authStatusRoute, /\.eq\("user_id",\s*userId\)/);
  assert.match(authStatusRoute, /countAccountRows\(supabase,\s*"resume_projects",\s*userId\)/);
  assert.match(authStatusRoute, /countAccountRows\(supabase,\s*"support_requests",\s*userId\)/);
  assert.match(authStatusRoute, /accountSummary/);
  assert.match(authStatusRoute, /savedProjectCount/);
  assert.match(authStatusRoute, /supportRequestCount/);
  assert.match(authStatusRoute, /isSupportAdminUser/);
  assert.match(authStatusRoute, /operations/);
  assert.match(authStatusRoute, /supportAdmin:\s*Boolean\(data\.user && isSupportAdminUser\(data\.user\)\)/);
  assert.doesNotMatch(authStatusRoute, /ROLEFORGE_ADMIN_EMAILS[^;]*json/i);
});

test("help status support and updates mount the public account menu", () => {
  for (const source of [helpPage, statusPage, supportPage, updatesPage]) {
    assert.match(source, /PublicAccountMenu/);
    assert.match(source, /supportHref=\{supportRequestHref\(/);
  }
  assert.match(helpPage, /subject:\s*"Help center question"/);
  assert.match(statusPage, /subject:\s*"Status page question"/);
  assert.match(supportPage, /subject:\s*"Support page question"/);
  assert.match(updatesPage, /subject:\s*"Product updates question"/);
});

test("public account menu topbar layout is overflow safe", () => {
  assert.match(stylesheet, /\.public-account-menu\s*\{(?=[^}]*z-index:\s*32)[^}]*\}/s);
  assert.match(stylesheet, /\.public-account-signin\s*\{(?=[^}]*flex:\s*0\s+0\s+auto)[^}]*\}/s);
  assert.match(stylesheet, /\.public-account-loading\s*\{(?=[^}]*flex:\s*0\s+0\s+auto)(?=[^}]*cursor:\s*wait)(?=[^}]*pointer-events:\s*none)[^}]*\}/s);
  assert.match(stylesheet, /\.public-account-loading\s+>\s+span\[aria-hidden="true"\]\s*\{(?=[^}]*width:\s*15px)(?=[^}]*height:\s*15px)(?=[^}]*animation:\s*public-account-loading-spin)[^}]*\}/s);
  assert.match(stylesheet, /@keyframes\s+public-account-loading-spin/);
  assert.match(stylesheet, /@media\s*\(prefers-reduced-motion:\s*reduce\)\s*\{[\s\S]*?\.public-account-loading\s+>\s+span\[aria-hidden="true"\]\s*\{[^}]*animation:\s*none/s);
  assert.match(stylesheet, /html\[data-theme="dark"\]\s+\.public-account-loading/);
  assert.match(stylesheet, /\.public-topbar-avatar\s*\{(?=[^}]*width:\s*40px)(?=[^}]*height:\s*40px)[^}]*\}/s);
  assert.match(stylesheet, /\.public-account-popover\s*\{(?=[^}]*width:\s*min\(420px,\s*calc\(100vw\s*-\s*30px\)\))[^}]*\}/s);
  assert.match(stylesheet, /\.public-account-reference,\s*\.studio-account-reference\s*\{(?=[^}]*display:\s*flex)(?=[^}]*flex-wrap:\s*wrap)(?=[^}]*max-width:\s*100%)[^}]*\}/s);
  assert.match(stylesheet, /\.public-account-reference\s*>\s*span,\s*\.studio-account-reference\s*>\s*span\s*\{(?=[^}]*font-size:\s*0\.74rem)(?=[^}]*overflow-wrap:\s*anywhere)[^}]*\}/s);
  assert.match(stylesheet, /\.public-account-reference-copy,\s*\.studio-account-reference-copy\s*\{(?=[^}]*display:\s*inline-flex)(?=[^}]*min-height:\s*26px)(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*white-space:\s*normal)[^}]*\}/s);
  assert.match(stylesheet, /\.studio-account-next-actions\s*\{(?=[^}]*display:\s*grid)(?=[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\))(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(stylesheet, /\.studio-account-next-actions\s+a\s*\{(?=[^}]*min-height:\s*42px)(?=[^}]*min-width:\s*0)(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*text-wrap:\s*balance)(?=[^}]*white-space:\s*normal)[^}]*\}/s);
  assert.match(stylesheet, /@container\s+studio-account-popover\s+\(max-width:\s*360px\)\s*\{[\s\S]*?\.studio-account-insights,\s*\.studio-account-next-actions\s*\{[^}]*grid-template-columns:\s*1fr/s);
  assert.match(stylesheet, /html\[data-theme="dark"\]\s+\.studio-account-next-actions a/);
  assert.match(stylesheet, /html\[data-theme="dark"\]\s+\.studio-account-next-actions a:first-child/);
  assert.match(stylesheet, /\.public-account-shortcuts,\s*\.public-account-utilities\s*\{(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(stylesheet, /\.public-account-shortcuts\s+a,\s*\.public-account-utilities\s+a\s*\{(?=[^}]*min-width:\s*0)(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*text-wrap:\s*balance)(?=[^}]*white-space:\s*normal)[^}]*\}/s);
  assert.match(stylesheet, /html\[data-theme="dark"\]\s+\.public-account-reference-copy/);
});
