import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const updatesPage = readFileSync("app/updates/page.tsx", "utf8");
const landingPage = readFileSync("app/page.tsx", "utf8");
const helpPage = readFileSync("app/help/page.tsx", "utf8");
const statusPage = readFileSync("app/status/page.tsx", "utf8");
const supportPage = readFileSync("app/support/page.tsx", "utf8");
const studioPage = readFileSync("app/app/page.tsx", "utf8");
const settingsPage = readFileSync("app/settings/page.tsx", "utf8");
const templatesPage = readFileSync("app/templates/page.tsx", "utf8");
const legalPage = readFileSync("app/components/LegalPage.tsx", "utf8");
const robotsRoute = readFileSync("app/robots.ts", "utf8");
const sitemapRoute = readFileSync("app/sitemap.ts", "utf8");
const stylesheet = readFileSync("app/globals.css", "utf8");
const smokeFrontend = readFileSync("scripts/smoke_frontend.mjs", "utf8");
const smokeLayout = readFileSync("scripts/smoke_layout.mjs", "utf8");

test("updates page is a factual public product log", () => {
  assert.match(updatesPage, /title: "Product Updates"/);
  assert.match(updatesPage, /canonical: "\/updates"/);
  assert.match(updatesPage, /What changed in RoleForge/);
  assert.match(updatesPage, /A factual log of shipped workflow, account, export, and billing improvements/);
  assert.match(updatesPage, /updatePrinciples/);
  assert.match(updatesPage, /Published only after behavior ships/);
  assert.match(updatesPage, /Grouped by release theme, not every small patch/);
  assert.match(updatesPage, /No unsupported claims or roadmap promises/);
  assert.match(updatesPage, /Short, grouped, and shipped/);
  assert.match(updatesPage, /Operational availability stays on Status/);
  assert.match(updatesPage, /June 2026/);
  assert.match(updatesPage, /Account controls are now more complete/);
  assert.match(updatesPage, /Communication preferences are saved to the account profile and included in account exports/);
  assert.match(updatesPage, /Data and privacy controls route export, deletion, policy, and support questions/);
  assert.match(updatesPage, /Support and status paths are clearer/);
  assert.match(updatesPage, /Support requests are saved to the signed-in account with a safe RF reference/);
  assert.match(updatesPage, /privacy questions open prefilled support requests/);
  assert.match(updatesPage, /Premium and export behavior is explicit/);
  assert.match(updatesPage, /separates free PDF export from Premium DOCX\/TXT access/);
  assert.match(updatesPage, /Checkout and billing management use Stripe/);
  assert.match(updatesPage, /Saved work is easier to recover/);
  assert.match(updatesPage, /Project rows now keep stage controls, downloads, restore actions, and removal controls readable/);
  assert.match(updatesPage, /Public guidance is easier to scan/);
  assert.match(updatesPage, /Help, Status, Templates, Support, Updates, Privacy, and Terms/);
  assert.match(updatesPage, /May 2026/);
  assert.match(updatesPage, /Template direction is visible before Studio/);
  assert.match(updatesPage, /Template choices carry into new studio runs and exports/);
  assert.match(updatesPage, /actionHref: "\/settings#projects"/);
  assert.match(updatesPage, /actionHref: "\/settings"/);
  assert.match(updatesPage, /actionHref: "\/help"/);
  assert.match(updatesPage, /actionHref: "\/support"/);
  assert.match(updatesPage, /actionHref: "\/settings#billing"/);
  assert.match(updatesPage, /actionHref: "\/templates"/);
  assert.match(updatesPage, /updates-overview/);
  assert.match(updatesPage, /updates-card-actions/);
  assert.equal((updatesPage.match(/date: "/g) ?? []).length, 6);
  assert.doesNotMatch(updatesPage, /trusted by|customers|guaranteed|ATS pass|human coach|live roadmap/i);
});

test("updates page is discoverable from public and signed-in surfaces", () => {
  assert.match(landingPage, /href="\/updates"/);
  assert.match(helpPage, /href="\/updates"/);
  assert.match(statusPage, /href="\/updates"/);
  assert.match(supportPage, /href="\/status"/);
  assert.match(studioPage, /href="\/updates"/);
  assert.match(settingsPage, /href="\/updates"/);
  assert.match(templatesPage, /href="\/updates"/);
  assert.match(legalPage, /href="\/updates"/);
  assert.match(robotsRoute, /"\/updates"/);
  assert.match(robotsRoute, /"\/support"/);
  assert.match(sitemapRoute, /`\$\{siteUrl\}\/updates`/);
  assert.match(sitemapRoute, /`\$\{siteUrl\}\/support`/);
  assert.match(smokeFrontend, /sitemap\.text\.includes\(`\$\{canonicalUrl\}\/updates`\)/);
  assert.match(smokeLayout, /path: "\/updates"/);
});

test("updates timeline has overflow-safe responsive cards", () => {
  assert.match(stylesheet, /\.updates-overview\s*\{(?=[^}]*display:\s*grid)(?=[^}]*grid-template-columns:\s*minmax\(0,\s*0\.62fr\)\s+minmax\(0,\s*1fr\))(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(stylesheet, /\.updates-timeline\s*\{(?=[^}]*display:\s*grid)(?=[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\))(?=[^}]*gap:\s*14px)(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(stylesheet, /\.updates-card\s*\{(?=[^}]*container:\s*updates-card\s*\/\s*inline-size)(?=[^}]*grid-template-columns:\s*48px\s+minmax\(0,\s*1fr\))(?=[^}]*overflow:\s*hidden)[^}]*\}/s);
  assert.match(stylesheet, /\.updates-card-meta\s*\{(?=[^}]*display:\s*flex)(?=[^}]*flex-wrap:\s*wrap)(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(stylesheet, /\.updates-card\s+h2\s*\{(?=[^}]*font-size:\s*1\.9rem)(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*text-wrap:\s*balance)[^}]*\}/s);
  assert.match(stylesheet, /\.updates-card\s+li\s*\{(?=[^}]*grid-template-columns:\s*16px\s+minmax\(0,\s*1fr\))(?=[^}]*overflow-wrap:\s*anywhere)(?=[^}]*text-wrap:\s*pretty)[^}]*\}/s);
  assert.match(stylesheet, /\.updates-card-actions\s*\{(?=[^}]*display:\s*flex)(?=[^}]*flex-wrap:\s*wrap)(?=[^}]*min-width:\s*0)[^}]*\}/s);
  assert.match(stylesheet, /\.updates-card-actions\s+\.btn\s*\{(?=[^}]*max-width:\s*100%)(?=[^}]*text-wrap:\s*balance)(?=[^}]*white-space:\s*normal)[^}]*\}/s);
  assert.match(stylesheet, /@container\s+updates-card\s+\(max-width:\s*520px\)/);
  assert.match(stylesheet, /@media\s*\(max-width:\s*900px\)\s*\{[\s\S]*?\.updates-overview,[\s\S]*?\.updates-timeline\s*\{[^}]*grid-template-columns:\s*1fr/s);
  assert.match(stylesheet, /html\[data-theme="dark"\]\s+\.updates-card/);
});
